### ISSUE TITLE
Create print ready PDF files of BC Laws

### ISSUE THREAD

**Issue by lmullane** [bcgov/bc-laws-api#8]
<a rel="Inspiration" href="https://github.com/BCDevExchange/docs/blob/master/discussion/projectstates.md"><img alt="An idea being explored and shaped. Open for discussion, but may never go anywhere." style="border-width:0" src="http://bcdevexchange.org/badge/1.svg" title="An idea being explored and shaped. Open for discussion, but may never go anywhere." /></a> 
# Story:

As a citizen, I would like to access a typeset PDF document of all the acts and regulations of British Columbia so I can print them. 
# Additional detail:

The Queen’s Printer of British Columbia has converted all legislation in British Columbia to an XML format and given access to this information through an open API. We would like to leverage this XML data to create print ready PDF files. Some work has been done on this by creating xsl style-sheets (.xsl files) that convert the source xml document to an xsl-fo (.fo) file. The resulting xsl-fo file will then be transformed by Apache FOP into a pdf document.
We have supplied pdf examples and inDesign templates as style guidelines for how the final pdfs should look. Additial xml examples can be obtained through the BCLaws API located here: www.bclaws.ca  and documented here: www.bclaws.ca/documentation.

The process we require is as follows:
1. Create xsl file(s) that transforms the xml input into xsl-fo markup. `(input.xml -> transform_to_fo.xsl -> result.fo)`

The xsl files you create must be compliant with the criteria outlined below. We only require the xsl to successfully generate the .fo files and not any supporting transform specific
code you have written. For writing and testing the xsl we suggest using an editor which supports transformation using [Saxon](http://saxon.sourceforge.net/) such as [Oxygen xml editor](https://www.oxygenxml.com/) or 
one of the many open source alternatives listed [here](https://en.wikipedia.org/wiki/Comparison_of_XML_editors). Your resulting .fo file can then be
tested using [Apache FOP](https://xmlgraphics.apache.org/fop/) to see the resulting pdf output.

The xsl files we have supplied are to be used as guidelines but you may use the code in your own implemetation.
# Acceptance criteria:

The story will be considered complete when:
The xsl files you write can be used to generate .fo files that can be used to create pdfs to match the format of the InDesign files we supplied.  The resulting PDFs should match the font, styles and content of the InDesign files located in the [docs directory](https://github.com/bcgov/bc-laws-api/tree/master/docs)

Attached you will find source XML for 2 Acts, and 2 Regulations.  Your solution should be able to accuratly transform these source documents into resultant .fo file.

XSL files should be written using [XSLT 2.0](http://www.w3.org/TR/xslt20/) and be compliant with a Saxon transformer.
XSL files should well documented and follow best coding practices such as those found [here](http://www.xml.org//sites/www.xml.org/files/xslt_efficient_programming_techniques.pdf). 

Source XML is available at the following link: [Source XML.zip](https://github.com/bcgov/bc-laws-api/files/68910/Source.XML.zip)
# Please read the [Contributing file](https://github.com/bcgov/bc-laws-api/blob/master/CONTRIBUTING.md) for how to participate.

We would love to here from you. Please post your questions in the comments below.

**Comment by AlexStrudwick** [comment]
Hello everyone,

I would be happy to answer questions related to this project.  Please let me know if I can clarify anything for you.

Thanks everyone,
Alex Strudwick
Supervisor, Information Systems and Application Development
Queen's Printer, Digital Publishing
Shared Services BC | Technology, Innovation and Citizens' Services
563 Superior St, Victoria BC V8W 9V7

**Comment by lmullane** [comment]
Test

**Comment by lmullane** [comment]
test

**Comment by m-sinclair** [comment]
Hi Alex,

Just to clarify so that I know that I am heading in the right direction.
- I'm using FOP to transform several XML documents into 4 pdfs
- FOP does this by taking an XSL and transforming that into a FO doc.
- The XSL's that I'm using are 'bcl.xsl, includes,xsl, act.xsl, in.xsl'

When you say "modify the draft stylesheet" are you referring to turning that into a xsl-fo? I've noticed that the xsl's have many problems with them. The example pdf from the 'inDesign Docs' has these problems as well. E.g.

Unmatched [bcl:clause] Athe structure of a building;
UnMatched [bcl:clause] Bthe exterior of a building;
UnMatched [bcl:clause] Cchimneys, stairs, balconies and other things attached to
the exterior of a building;
UnMatched [bcl:clause] Ddoors, windows and skylights on the exterior of a building
or that front on the common property;
UnMatched [bcl:clause] Efences, railings and similar structures that enclose patios,
balconies and yards;

Is this story to add to/fix issues in the existing xsl, or should this be working already? Could you please expand on the phrase "modify the draft stylesheet".

Mike

**Comment by m-sinclair** [comment]
To add to my questions above:
-The InDesign file "AccessToAbortion.xml" and "AccessToAbortion.fo" appear to be the same.

**Comment by AlexStrudwick** [comment]
Hi everyone,

We have updated the details and acceptance criteria for this task.  Please see above for details.

Thanks everyone,
Alex Strudwick
Supervisor, Information Systems and Application Development
Queen's Printer, Digital Publishing
Shared Services BC | Technology, Innovation and Citizens' Services
563 Superior St, Victoria BC V8W 9V7

**Comment by cditcher** [comment]
Hi Mike. In response to your questions we have updated the story to be what we hope is more clear. The basic requirement is to write an xsl style-sheet(s) which transforms an input document (any act or reg xml file) into an .fo markup file. 

The resulting .fo file can then be transformed into a pdf file using Apache FOP. We will be doing this step ourselves server-side but using the same Apache FOP API. The xsl files we provided are meant to be used as a guideline, or if you wish you can use them to create your own implementation based on the code they contain.

**Comment by AlexStrudwick** [comment]
BC Developer's Exchange test is now complete.  Thanks to all for participating.

Thanks everyone,
Alex Strudwick
Supervisor, Information Systems and Application Development
Queen's Printer, Digital Publishing
Shared Services BC | Technology, Innovation and Citizens' Services
563 Superior St, Victoria BC V8W 9V7
